import matplotlib.pyplot as plt
import numpy as np
from scipy import signal
x=np.linspace(0,10*np.pi,200)
y=np.sin(x)
z=signal.sawtooth(x)
c=signal.square(x)
plt.subplot(3, 1, 1)
plt.plot(x,y)
plt.title("Wykres przebiegu sinusoidalnego")
plt.xlabel("Kąt["+r'$rad$'+"]")
plt.ylabel("Amplituda")
plt.yticks((-1,-0.5,0,0.5,1))
plt.xticks([0, np.pi, 2*np.pi,3*np.pi, 4*np.pi, 5*np.pi, 6*np.pi, 7*np.pi, 8*np.pi, 9*np.pi, 10*np.pi],('0',r'$\pi$',r'$2\pi$',r'$3\pi$',r'$4\pi$',r'$5\pi$',r'$6\pi$',r'$7\pi$',r'$8\pi$',r'$9\pi$',r'$10\pi$'))
plt.subplot(3, 1, 2)
plt.title("Wykres przebiegu piłokształtnego")
plt.xlabel("Kąt["+r'$rad$'+"]")
plt.ylabel("Amplituda")
plt.plot(x,z)
plt.yticks((-1,-0.5,0,0.5,1))
plt.xticks([0, np.pi, 2*np.pi,3*np.pi, 4*np.pi, 5*np.pi, 6*np.pi, 7*np.pi, 8*np.pi, 9*np.pi, 10*np.pi],('0',r'$\pi$',r'$2\pi$',r'$3\pi$',r'$4\pi$',r'$5\pi$',r'$6\pi$',r'$7\pi$',r'$8\pi$',r'$9\pi$',r'$10\pi$'))
plt.subplot(3, 1, 3)
plt.title("Wykres przebiegu prostokątnego")
plt.xlabel("Kąt["+r'$rad$'+"]")
plt.ylabel("Amplituda")
plt.plot(x,c)
plt.yticks((-1,-0.5,0,0.5,1))
plt.xticks([0, np.pi, 2*np.pi,3*np.pi, 4*np.pi, 5*np.pi, 6*np.pi, 7*np.pi, 8*np.pi, 9*np.pi, 10*np.pi],('0',r'$\pi$',r'$2\pi$',r'$3\pi$',r'$4\pi$',r'$5\pi$',r'$6\pi$',r'$7\pi$',r'$8\pi$',r'$9\pi$',r'$10\pi$'))
plt.tight_layout()
plt.show()